name: Trigger auto deployment for aca-tccc-gcc-cloud-connect-qa

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aca-tccc-gcc-cloud-connect-qa-AutoDeployTrigger-26d97a8c-5202-4413-9c58-b352aa5ef5c7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ACATCCCGCCCLOUDCONNECTQA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACATCCCGCCCLOUDCONNECTQA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACATCCCGCCCLOUDCONNECTQA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acrtcccgccqa01.azurecr.io
          registryUsername: ${{ secrets.ACATCCCGCCCLOUDCONNECTQA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACATCCCGCCCLOUDCONNECTQA_REGISTRY_PASSWORD }}
          containerAppName: aca-tccc-gcc-cloud-connect-qa
          resourceGroup: rg-tccc-gep-cloud-connect-qa
          imageToBuild: acrtcccgccqa01.azurecr.io/aca-tccc-gcc-cloud-connect-qa:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


